identifiers {
  type: CUSTOM
  details:'reaction index'
  value: 'index'
}


identifiers {
  type: NAME
  details:'reaction type'
  value: '$reaction_type$'
}



inputs {
  key: "amine"
  value {
    components {
      identifiers {
        type: SMILES
        value: "$Amine$"
      }
      amount {
        moles {
          value: $Amine_amount$
          units: MOLE
        }
      }
      reaction_role: REACTANT
      is_limiting: false
  
    }
    
  }
}


inputs {
  key: "aryl halide"
  value {
    components {
      identifiers {
        type: SMILES
        value: "$Halide$"
      }
      amount {
        moles {
          value: $Halide_amount$
          units: MOLE
        }
      }
      reaction_role: REACTANT
      is_limiting: false
    }
    
  }
}
inputs {
  key: "metal and ligand"
  value {
    components {
      identifiers {
        type: SMILES
        value: "$Ligand$"
      }
      amount {
        moles {
          value:$Ligand_amount$
          units: MOLE
        }
      }
      reaction_role: CATALYST
      is_limiting: false
      
    }
  components {
      identifiers {
        type: SMILES
        value: "$Metal$"
      }
      amount {
        moles {
          value: $Ligand_amount$
          units: MOLE
        }
      }
      reaction_role: CATALYST
      is_limiting: false
      
    }
	
   

  }
}


inputs {
  key: "Base"
  value {
    components {
      identifiers {
        type: SMILES
        value: "$Base$"
      }
      amount {
        moles {
          value:  $base_amount$
          units: MOLE
        }
      }
      reaction_role: REAGENT
      is_limiting: false
      
    }
   

  }
}


inputs {
  key: "Solvent"
  value {
    components {
      identifiers {
        type: SMILES
        value: "$Solvent$"
      }
      amount {
        volume {
          value:$Reaction_volume$
          units: LITER
        }
      }
      reaction_role: SOLVENT
      is_limiting: false
      
    }
   

  }
}


conditions {

  temperature {
      setpoint {
        value: $Temperature$
        precision: 10
        units: CELSIUS
      }
    }
 
  
}



notes{

	procedure_details:'Note'

	

}


outcomes {
  
  products {
    identifiers {
      type: SMILES
      value: "$Product$"
    }
    is_desired_product: true
    measurements {
      type: YIELD
      percentage {
        value: $Yield$
      }
    }
    reaction_role: PRODUCT
  }
}

provenance {
   experimenter {
    organization: "AstraZeneca" 
      }
    experiment_start {
    value: "$created_date$"
  }

  
  publication_url: "https://chemrxiv.org/engage/chemrxiv/article-details/60c9e3f37792a23bfdb2d471"
  record_created {
    time {
      value: "10/19/2021, 12:16:25 PM"
    }
    person {
      name: "Bozhao Nan"
      organization: "Notre Dame"
      email: "bnan@nd.edu"
    }
  }
}
