identifiers {
  type: NAME
  details: "https://doi.org/10.1038/s41586-021-03213-y"
  value: "Imidazole Arylation, Figure S42"
}
inputs {
  key: "Base"
  value {
    components {
      identifiers {
        type: SMILES
        value: "$Base_SMILES$"
      }
      amount {
        moles {
          value: 0.045
          units: MILLIMOLE
        }
      }
      reaction_role: REAGENT
      preparations {
        type: DRIED
      }
    }
    addition_order: 1
  }
}
inputs {
  key: "Stock Solution of Ligand, Pd, Aryl bromide, internal standard, and imidazole in solvent - see SI for details"
  value {
    components {
      identifiers {
        type: SMILES
        value: "$Ligand_SMILES$"
      }
      amount {
        moles {
          value: 0.75
          units: MICROMOLE
        }
      }
      reaction_role: CATALYST
      preparations {
        type: DRIED
      }
    }
    components {
      identifiers {
        type: SMILES
        value: "$Solvent_SMILES$"
      }
      amount {
        volume {
          value: $Solvent_added$
          units: MICROLITER
        }
        volume_includes_solutes: true
      }
      reaction_role: SOLVENT
      preparations {
        type: DRIED
      }
    }
    components {
      identifiers {
        type: SMILES
        value: "C=C[CH2-].C=C[CH2-].Cl[Pd+].Cl[Pd+]"
      }
      amount {
        moles {
          value: 0.338
          units: MICROMOLE
        }
      }
      reaction_role: CATALYST
    }
    components {
      identifiers {
        type: SMILES
        value: "Cn1cnc(C#N)c1"
      }
      amount {
        moles {
          value: 0.03
          units: MILLIMOLE
        }
      }
      reaction_role: REACTANT
      is_limiting: false
      preparations {
        type: DRIED
      }
    }
    components {
      identifiers {
        type: SMILES
        value: "Fc1ccccc1Br"
      }
      amount {
        moles {
          value: 0.015
          units: MILLIMOLE
        }
      }
      reaction_role: REACTANT
      is_limiting: true
      preparations {
        type: DRIED
      }
    }
    components {
      identifiers {
        type: SMILES
        value: "CC(C)(C)c1ccc(-c2ccc(C(C)(C)C)cc2)cc1"
      }
      amount {
        moles {
          value: 0.015
          units: MILLIMOLE
        }
      }
      reaction_role: INTERNAL_STANDARD
      preparations {
        type: DRIED
      }
    }
    addition_order: 2
    addition_speed {
      type: ALL_AT_ONCE
      details: "Solution without imidazole was allowed to stir in larger stock solutions for 30 min. See SI for details"
    }
  }
}
setup {
  vessel {
    type {
      type: WELL_PLATE
    }
  }
  environment {
    type: GLOVE_BOX
  }
}
conditions {
  temperature {
    setpoint {
      value: $Temp_C$
      units: CELSIUS
    }
  }
  pressure {
    control {
      type: SEALED
    }
  }
  stirring {
    method {
      type: AGITATION
    }
  }
}
workups {
  type: ALIQUOT
  details: "The plate was removed from the glovebox, opened, and diluted to a 900 uL total volume with N,N-dimethylacetamide. The plate was stirred for 5 min and a 75 uL sample was taken and filtered into an HPLC analysis plate. The filter was rinsed with 400 uL acetonitrile/water (4:1) solution and analyzed by UHPLCMS"
  amount {
    volume {
      value: 75.0
      units: MICROLITER
    }
  }
}
outcomes {
  reaction_time {
    value: 24.0
    units: HOUR
  }
  products {
    identifiers {
      type: SMILES
      value: "N#CC1=C(C2=CC=CC=C2F)N(C)C=N1"
    }
    is_desired_product: true
    measurements {
      analysis_key: "UHPLCMS"
      type: YIELD
      details: "See SI for Calibration Curve"
      uses_internal_standard: true
      is_normalized: true
      percentage {
        value: $yield$
      }
    }
    reaction_role: PRODUCT
  }
  analyses {
    key: "UHPLCMS"
    value {
      type: LC
      details: "Solvent A: Water with 5% acetonitrile and 0.05% TFA\nSolvent B: acetonitrile with 5% water and 0.05% TFA\nGradient: 95% A/B to 5% A/B over 2.5 min, hold 1.0 min at 95% B\nStop Time: 3.5 min\nFlow Rate: 0.8 mL/min\nWavelength1: 220\nWavelength2: 254\nColumn: Agilent Poroshell C18 2.7 um 2.1x50mm\nOven Temperature: 40"
      is_of_isolated_species: false
    }
  }
}
outcomes {
  reaction_time {
    value: 24.0
    units: HOUR
  }
  products {
    identifiers {
      type: SMILES
      value: "CC(C1=CC=C(C2=CC=C(C(C)(C)C)C=C2)C=C1)(C)C"
    }
    reaction_role: INTERNAL_STANDARD
  }
}
provenance {
  experimenter {
    organization: "Princeton University"
  }
  city: "Princeton NJ"
  record_created {
    time {
      value: "2/4/2021, 11:24:34 AM"
    }
    person {
      name: "Jesus Martinez"
      organization: "Princeton"
      email: "jima@princeton.edu"
    }
  }
}
