# Runs process_dataset.py on all files in the database.

name: Validation

on:
  push:
    branches:
      - main
  schedule:
    # Runs every night at midnight.
    - cron: '0 0 * * *'
  pull_request:
    paths:
      # Runs when this file is modified in a PR.
      - '.github/workflows/validation.yml'

env:
  ORD_SCHEMA_TAG: v0.2.7

jobs:
  validate_database:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ord-data
      uses: actions/checkout@v2
    - name: Checkout ord-schema
      uses: actions/checkout@v2
      with:
        repository: Open-Reaction-Database/ord-schema
        ref: ${{ env.ORD_SCHEMA_TAG }}
        path: ord-schema
    - name: Install miniconda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        cd "${GITHUB_WORKSPACE}/ord-schema"
        pip install -r requirements.txt
        conda install -c rdkit rdkit
        python setup.py install
    - name: Validate datasets
      run: |
        cd "${GITHUB_WORKSPACE}"
        python ./ord-schema/ord_schema/process_dataset.py \
          --input_pattern="data/*/*.pb"
